-- Requests stay separate from published topics until their scope/content is ready.
CREATE TABLE topic_request (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES app_user(id),
    category_id bigint NOT NULL REFERENCES topic(id),
    name varchar(120) NOT NULL CHECK (btrim(name) <> ''),
    normalized_name varchar(120) NOT NULL CHECK (btrim(normalized_name) <> ''),
    scope varchar(1000) NOT NULL CHECK (char_length(scope) BETWEEN 10 AND 1000),
    status varchar(40) NOT NULL DEFAULT 'NEEDS_REVIEW' CHECK (status = 'NEEDS_REVIEW'),
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (user_id, category_id, normalized_name)
);
CREATE INDEX topic_request_user_recent ON topic_request(user_id, id DESC);
