-- Keep the observation-based model separate from saved legacy ranking results.
CREATE TABLE learning_recommendation (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES app_user(id),
    topic_id bigint NOT NULL REFERENCES topic(id),
    profile_id bigint NOT NULL REFERENCES reader_profile(id),
    request_key varchar(200) NOT NULL,
    request_hash varchar(64) NOT NULL,
    input_snapshot jsonb NOT NULL CHECK (jsonb_typeof(input_snapshot) = 'object'),
    result jsonb NOT NULL CHECK (jsonb_typeof(result) = 'object'),
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (user_id, request_key)
);
