ALTER TABLE topic ADD COLUMN ml_topic_id varchar(120);
CREATE UNIQUE INDEX topic_ml_topic_id_unique ON topic(ml_topic_id) WHERE ml_topic_id IS NOT NULL;
UPDATE topic SET ml_topic_id = 'operating-systems' WHERE code = 'OS';
UPDATE topic SET ml_topic_id = 'linear-algebra' WHERE code = 'LA';

ALTER TABLE book ADD COLUMN ml_book_id varchar(200);
CREATE UNIQUE INDEX book_ml_book_id_unique ON book(ml_book_id) WHERE ml_book_id IS NOT NULL;

CREATE TABLE book_ranking_v2_projection (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id bigint NOT NULL,
    topic_id bigint NOT NULL,
    version varchar(80) NOT NULL CHECK (btrim(version) <> ''),
    active boolean NOT NULL DEFAULT false,
    topic_distribution jsonb NOT NULL CHECK (jsonb_typeof(topic_distribution) = 'object'),
    covered_concepts jsonb NOT NULL CHECK (jsonb_typeof(covered_concepts) = 'array'),
    prerequisite_concepts jsonb NOT NULL CHECK (jsonb_typeof(prerequisite_concepts) = 'array'),
    lexical_difficulty double precision CHECK (lexical_difficulty BETWEEN 0 AND 1),
    syntactic_complexity double precision CHECK (syntactic_complexity BETWEEN 0 AND 1),
    concept_density double precision CHECK (concept_density BETWEEN 0 AND 1),
    prerequisite_demand double precision CHECK (prerequisite_demand BETWEEN 0 AND 1),
    config_version varchar(80) NOT NULL CHECK (btrim(config_version) <> ''),
    config_hash varchar(71) NOT NULL CHECK (config_hash ~ '^sha256:[0-9a-f]{64}$'),
    source_artifact_version varchar(120) NOT NULL CHECK (btrim(source_artifact_version) <> ''),
    source_artifact_hash varchar(71) NOT NULL CHECK (source_artifact_hash ~ '^sha256:[0-9a-f]{64}$'),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    FOREIGN KEY (book_id, topic_id) REFERENCES book_topic(book_id, topic_id),
    UNIQUE (book_id, topic_id, version)
);
CREATE UNIQUE INDEX book_ranking_v2_projection_one_active
    ON book_ranking_v2_projection(book_id, topic_id) WHERE active;
CREATE INDEX book_ranking_v2_projection_topic_active
    ON book_ranking_v2_projection(topic_id, book_id) WHERE active;
CREATE TRIGGER book_ranking_v2_projection_updated BEFORE UPDATE ON book_ranking_v2_projection
FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

ALTER TABLE recommendation_run
    ADD COLUMN ranking_mode varchar(40) NOT NULL DEFAULT 'LEGACY_SCALAR'
        CHECK (ranking_mode IN ('LEGACY_SCALAR','PREREQUISITE_FIRST_V2')),
    ADD COLUMN ranking_config_version varchar(80),
    ADD COLUMN ranking_config_hash varchar(71),
    ADD COLUMN concept_graph_version varchar(80),
    ADD COLUMN concept_graph_hash varchar(71),
    ADD COLUMN graph_review_version varchar(80),
    ADD COLUMN graph_review_hash varchar(71),
    ADD COLUMN reader_profile_version varchar(80),
    ADD COLUMN reader_config_version varchar(80),
    ADD COLUMN reader_config_hash varchar(71),
    ADD COLUMN ranking_diagnostics jsonb;

ALTER TABLE recommendation_run ADD CONSTRAINT recommendation_run_v2_provenance CHECK (
    ranking_mode = 'LEGACY_SCALAR'
    OR status <> 'SUCCEEDED'
    OR (
        model_version = 'rank-prerequisite-first-v2'
        AND ranking_config_version IS NOT NULL
        AND ranking_config_hash ~ '^sha256:[0-9a-f]{64}$'
        AND concept_graph_version IS NOT NULL
        AND concept_graph_hash ~ '^sha256:[0-9a-f]{64}$'
        AND graph_review_version IS NOT NULL
        AND graph_review_hash ~ '^sha256:[0-9a-f]{64}$'
        AND reader_profile_version IS NOT NULL
        AND reader_config_version IS NOT NULL
        AND reader_config_hash ~ '^sha256:[0-9a-f]{64}$'
        AND jsonb_typeof(ranking_diagnostics) = 'object'
    )
);

ALTER TABLE recommendation_item
    ALTER COLUMN feature_id DROP NOT NULL,
    ALTER COLUMN score DROP NOT NULL,
    ALTER COLUMN topic_fit DROP NOT NULL,
    ALTER COLUMN vocabulary_fit DROP NOT NULL,
    ALTER COLUMN knowledge_fit DROP NOT NULL,
    ALTER COLUMN comprehension_fit DROP NOT NULL,
    ALTER COLUMN vocabulary_requirement DROP NOT NULL,
    ALTER COLUMN knowledge_requirement DROP NOT NULL,
    ALTER COLUMN comprehension_requirement DROP NOT NULL,
    ALTER COLUMN topic_relevance DROP NOT NULL,
    ADD COLUMN ranking_mode varchar(40) NOT NULL DEFAULT 'LEGACY_SCALAR'
        CHECK (ranking_mode IN ('LEGACY_SCALAR','PREREQUISITE_FIRST_V2')),
    ADD COLUMN projection_id bigint REFERENCES book_ranking_v2_projection(id),
    ADD COLUMN prerequisite_readiness double precision CHECK (prerequisite_readiness BETWEEN 0 AND 1),
    ADD COLUMN prerequisite_assessed_count int CHECK (prerequisite_assessed_count >= 1),
    ADD COLUMN prerequisite_total_count int CHECK (prerequisite_total_count >= 1),
    ADD COLUMN prerequisite_coverage double precision CHECK (prerequisite_coverage > 0 AND prerequisite_coverage <= 1),
    ADD COLUMN direct_learning_opportunity double precision CHECK (direct_learning_opportunity BETWEEN 0 AND 1),
    ADD COLUMN direct_assessed_count int CHECK (direct_assessed_count >= 0),
    ADD COLUMN direct_total_count int CHECK (direct_total_count >= 1),
    ADD COLUMN direct_coverage double precision CHECK (direct_coverage BETWEEN 0 AND 1),
    ADD COLUMN availability_status varchar(30),
    ADD COLUMN covered_concepts jsonb,
    ADD COLUMN inferred_prerequisites jsonb,
    ADD COLUMN book_config_version varchar(80),
    ADD COLUMN book_config_hash varchar(71);

ALTER TABLE recommendation_item ADD CONSTRAINT recommendation_item_mode_shape CHECK (
    (
        ranking_mode = 'LEGACY_SCALAR'
        AND feature_id IS NOT NULL AND projection_id IS NULL
        AND score IS NOT NULL AND topic_fit IS NOT NULL
        AND vocabulary_fit IS NOT NULL AND knowledge_fit IS NOT NULL
        AND comprehension_fit IS NOT NULL
        AND vocabulary_requirement IS NOT NULL AND knowledge_requirement IS NOT NULL
        AND comprehension_requirement IS NOT NULL AND topic_relevance IS NOT NULL
        AND prerequisite_readiness IS NULL AND prerequisite_assessed_count IS NULL
        AND prerequisite_total_count IS NULL AND prerequisite_coverage IS NULL
        AND direct_learning_opportunity IS NULL AND direct_assessed_count IS NULL
        AND direct_total_count IS NULL AND direct_coverage IS NULL
        AND availability_status IS NULL AND covered_concepts IS NULL
        AND inferred_prerequisites IS NULL AND book_config_version IS NULL
        AND book_config_hash IS NULL
    )
    OR
    (
        ranking_mode = 'PREREQUISITE_FIRST_V2'
        AND feature_id IS NULL AND projection_id IS NOT NULL
        AND score IS NULL AND topic_fit IS NULL AND vocabulary_fit IS NULL
        AND knowledge_fit IS NULL AND comprehension_fit IS NULL
        AND vocabulary_requirement IS NULL AND knowledge_requirement IS NULL
        AND comprehension_requirement IS NULL AND topic_relevance IS NULL
        AND prerequisite_readiness IS NOT NULL
        AND prerequisite_assessed_count <= prerequisite_total_count
        AND abs(prerequisite_coverage - prerequisite_assessed_count::double precision / prerequisite_total_count) < 1e-9
        AND direct_assessed_count <= direct_total_count
        AND abs(direct_coverage - direct_assessed_count::double precision / direct_total_count) < 1e-9
        AND ((direct_assessed_count = 0) = (direct_learning_opportunity IS NULL))
        AND availability_status = 'personalizable'
        AND jsonb_typeof(covered_concepts) = 'array'
        AND jsonb_typeof(inferred_prerequisites) = 'array'
        AND book_config_version IS NOT NULL
        AND book_config_hash ~ '^sha256:[0-9a-f]{64}$'
    )
);
