ALTER TABLE book_feature
    ADD CONSTRAINT book_feature_id_book_unique UNIQUE (id, book_id);

CREATE TABLE recommendation_run (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES app_user(id),
    topic_id bigint NOT NULL REFERENCES topic(id),
    profile_id bigint NOT NULL REFERENCES reader_profile(id),
    status varchar(20) NOT NULL CHECK (status IN ('PROCESSING','SUCCEEDED','FAILED')),
    request_key varchar(200) NOT NULL CHECK (btrim(request_key) <> ''),
    request_hash varchar(64) NOT NULL CHECK (request_hash ~ '^[0-9a-f]{64}$'),
    challenge_level varchar(20) NOT NULL
        CHECK (challenge_level IN ('COMFORTABLE','BALANCED','CHALLENGING')),
    target_book_id bigint REFERENCES book(id),
    requested_top_k int NOT NULL CHECK (requested_top_k BETWEEN 1 AND 20),
    attempt_id uuid,
    processing_expires_at timestamptz,
    input_snapshot jsonb NOT NULL CHECK (jsonb_typeof(input_snapshot) = 'object'),
    eligible_candidate_count int NOT NULL CHECK (eligible_candidate_count >= 0),
    excluded_candidate_count int NOT NULL CHECK (excluded_candidate_count >= 0),
    model_version varchar(80),
    last_failure_code varchar(40),
    last_failure_message text,
    failure_http_status int CHECK (failure_http_status BETWEEN 400 AND 599),
    completed_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (user_id, request_key),
    CHECK (
        (status = 'PROCESSING' AND attempt_id IS NOT NULL AND processing_expires_at IS NOT NULL)
        OR
        (status <> 'PROCESSING' AND attempt_id IS NULL AND processing_expires_at IS NULL)
    ),
    CHECK ((status = 'PROCESSING') = (completed_at IS NULL)),
    CHECK ((status = 'SUCCEEDED') = (model_version IS NOT NULL)),
    CHECK (
        (status = 'FAILED'
            AND last_failure_code IS NOT NULL
            AND last_failure_message IS NOT NULL
            AND failure_http_status IS NOT NULL)
        OR
        (status <> 'FAILED'
            AND last_failure_code IS NULL
            AND last_failure_message IS NULL
            AND failure_http_status IS NULL)
    )
);

CREATE INDEX recommendation_run_user_topic_created_idx
    ON recommendation_run(user_id, topic_id, created_at DESC, id DESC);

CREATE TABLE recommendation_item (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id bigint NOT NULL REFERENCES recommendation_run(id),
    book_id bigint NOT NULL REFERENCES book(id),
    feature_id bigint NOT NULL,
    rank int NOT NULL CHECK (rank > 0),
    score double precision NOT NULL CHECK (score BETWEEN 0 AND 1),
    topic_fit double precision NOT NULL CHECK (topic_fit BETWEEN 0 AND 1),
    vocabulary_fit double precision NOT NULL CHECK (vocabulary_fit BETWEEN 0 AND 1),
    knowledge_fit double precision NOT NULL CHECK (knowledge_fit BETWEEN 0 AND 1),
    comprehension_fit double precision NOT NULL CHECK (comprehension_fit BETWEEN 0 AND 1),
    book_feature_version varchar(80) NOT NULL CHECK (btrim(book_feature_version) <> ''),
    vocabulary_requirement double precision NOT NULL
        CHECK (vocabulary_requirement BETWEEN 0 AND 1),
    knowledge_requirement double precision NOT NULL
        CHECK (knowledge_requirement BETWEEN 0 AND 1),
    comprehension_requirement double precision NOT NULL
        CHECK (comprehension_requirement BETWEEN 0 AND 1),
    topic_relevance double precision NOT NULL CHECK (topic_relevance BETWEEN 0 AND 1),
    reasons jsonb NOT NULL
        CHECK (jsonb_typeof(reasons) = 'array' AND jsonb_array_length(reasons) >= 2),
    created_at timestamptz NOT NULL DEFAULT now(),
    FOREIGN KEY (feature_id, book_id) REFERENCES book_feature(id, book_id),
    UNIQUE (run_id, book_id),
    UNIQUE (run_id, rank)
);

CREATE INDEX recommendation_item_run_rank_idx ON recommendation_item(run_id, rank);

CREATE TABLE feedback (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recommendation_item_id bigint NOT NULL REFERENCES recommendation_item(id),
    user_id bigint NOT NULL REFERENCES app_user(id),
    helpful boolean NOT NULL,
    comment text CHECK (comment IS NULL OR char_length(comment) <= 1000),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (user_id, recommendation_item_id)
);

CREATE TRIGGER recommendation_run_updated BEFORE UPDATE ON recommendation_run
FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

CREATE TRIGGER feedback_updated BEFORE UPDATE ON feedback
FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
