-- Idempotency-Key-scoped recommendation runs. attempt_id/processing_expires_at mirror
-- assessment_session's ownership pattern so a slow/failed ML call can't be double-processed.
CREATE TABLE recommendation_run (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES app_user(id),
    topic_id bigint NOT NULL REFERENCES topic(id),
    profile_id bigint NOT NULL REFERENCES reader_profile(id),
    status varchar(20) NOT NULL CHECK (status IN ('PROCESSING','SUCCEEDED','FAILED')),
    request_key varchar(200) NOT NULL CHECK (btrim(request_key) <> ''),
    request_hash varchar(64) NOT NULL CHECK (btrim(request_hash) <> ''),
    attempt_id uuid,
    processing_expires_at timestamptz,
    model_version varchar(80),
    candidate_count int NOT NULL CHECK (candidate_count >= 0),
    excluded_count int NOT NULL CHECK (excluded_count >= 0),
    input_snapshot jsonb NOT NULL CHECK (jsonb_typeof(input_snapshot) = 'object'),
    last_failure_code varchar(40),
    last_failure_message text,
    completed_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE(user_id, request_key),
    CHECK (
        (status = 'PROCESSING' AND attempt_id IS NOT NULL AND processing_expires_at IS NOT NULL)
        OR
        (status <> 'PROCESSING' AND attempt_id IS NULL AND processing_expires_at IS NULL)
    ),
    CHECK ((status = 'SUCCEEDED') = (model_version IS NOT NULL AND completed_at IS NOT NULL))
);
CREATE INDEX recommendation_run_user_topic_idx ON recommendation_run(user_id, topic_id);

CREATE TABLE recommendation_item (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id bigint NOT NULL REFERENCES recommendation_run(id),
    book_id bigint NOT NULL REFERENCES book(id),
    feature_id bigint NOT NULL REFERENCES book_feature(id),
    rank int NOT NULL CHECK (rank >= 1),
    total_score double precision NOT NULL CHECK (total_score BETWEEN 0 AND 1),
    topic_fit double precision NOT NULL CHECK (topic_fit BETWEEN 0 AND 1),
    vocabulary_fit double precision NOT NULL CHECK (vocabulary_fit BETWEEN 0 AND 1),
    knowledge_fit double precision NOT NULL CHECK (knowledge_fit BETWEEN 0 AND 1),
    comprehension_fit double precision NOT NULL CHECK (comprehension_fit BETWEEN 0 AND 1),
    reasons jsonb NOT NULL CHECK (jsonb_typeof(reasons) = 'array'),
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE(run_id, book_id),
    UNIQUE(run_id, rank)
);

CREATE TRIGGER recommendation_run_updated BEFORE UPDATE ON recommendation_run
FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
