CREATE TABLE app_user (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    display_name varchar(120) NOT NULL CHECK (btrim(display_name) <> ''),
    demo_key varchar(80) UNIQUE,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE topic (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar(80) NOT NULL UNIQUE CHECK (btrim(code) <> ''),
    name varchar(120) NOT NULL CHECK (btrim(name) <> ''),
    parent_id bigint REFERENCES topic(id),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CHECK (parent_id <> id)
);
CREATE INDEX topic_parent_idx ON topic(parent_id);

-- Serialize hierarchy writers. READ COMMITTED trigger queries see preceding commits.
-- A guard-row update also forces stale REPEATABLE READ writers to abort rather than form a cycle.
CREATE TABLE topic_tree_guard (id integer PRIMARY KEY CHECK (id=1), revision bigint NOT NULL);
INSERT INTO topic_tree_guard VALUES (1,0);
CREATE FUNCTION lock_topic_tree() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    UPDATE backend.topic_tree_guard SET revision=revision+1 WHERE id=1;
    RETURN NULL;
END $$;
CREATE TRIGGER topic_tree_lock BEFORE INSERT OR UPDATE OR DELETE ON topic
FOR EACH STATEMENT EXECUTE FUNCTION lock_topic_tree();
CREATE FUNCTION check_topic_cycle() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF EXISTS (
        WITH RECURSIVE ancestors(id,parent_id) AS (
            SELECT id,parent_id FROM backend.topic WHERE id=NEW.parent_id
            UNION
            SELECT t.id,t.parent_id FROM backend.topic t JOIN ancestors a ON t.id=a.parent_id
        ) SELECT 1 FROM ancestors WHERE id=NEW.id
    ) THEN
        RAISE EXCEPTION 'topic cycle' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER topic_cycle AFTER INSERT OR UPDATE OF parent_id ON topic
FOR EACH ROW EXECUTE FUNCTION check_topic_cycle();

CREATE TABLE book (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(300) NOT NULL CHECK (btrim(title) <> ''),
    author varchar(200) NOT NULL CHECK (btrim(author) <> ''),
    description text NOT NULL,
    isbn varchar(20) UNIQUE CHECK (isbn IS NULL OR btrim(isbn) <> ''),
    demo_key varchar(80) UNIQUE,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE book_topic (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id bigint NOT NULL REFERENCES book(id),
    topic_id bigint NOT NULL REFERENCES topic(id),
    is_primary boolean NOT NULL DEFAULT false,
    topic_weight double precision NOT NULL CHECK (topic_weight BETWEEN 0 AND 1),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE(book_id,topic_id)
);
CREATE UNIQUE INDEX book_one_primary_topic ON book_topic(book_id) WHERE is_primary;
CREATE INDEX book_topic_lookup ON book_topic(topic_id,book_id);
CREATE TABLE book_sample (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id bigint NOT NULL REFERENCES book(id),
    source_url text,
    location varchar(200) NOT NULL,
    checksum varchar(64) NOT NULL,
    provenance text NOT NULL,
    synthetic boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE(book_id,checksum)
);
CREATE TABLE book_feature (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id bigint NOT NULL,
    topic_id bigint NOT NULL,
    version varchar(80) NOT NULL CHECK (btrim(version) <> ''),
    active boolean NOT NULL DEFAULT false,
    vocabulary double precision NOT NULL CHECK (vocabulary BETWEEN 0 AND 1),
    knowledge double precision NOT NULL CHECK (knowledge BETWEEN 0 AND 1),
    comprehension double precision NOT NULL CHECK (comprehension BETWEEN 0 AND 1),
    topic_relevance double precision NOT NULL CHECK (topic_relevance BETWEEN 0 AND 1),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    FOREIGN KEY(book_id,topic_id) REFERENCES book_topic(book_id,topic_id),
    UNIQUE(book_id,topic_id,version)
);
CREATE UNIQUE INDEX book_feature_one_active ON book_feature(book_id,topic_id) WHERE active;

CREATE FUNCTION touch_updated_at() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = clock_timestamp();
    RETURN NEW;
END $$;
CREATE TRIGGER app_user_updated BEFORE UPDATE ON app_user FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
CREATE TRIGGER topic_updated BEFORE UPDATE ON topic FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
CREATE TRIGGER book_updated BEFORE UPDATE ON book FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
CREATE TRIGGER book_topic_updated BEFORE UPDATE ON book_topic FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
CREATE TRIGGER book_sample_updated BEFORE UPDATE ON book_sample FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
CREATE TRIGGER book_feature_updated BEFORE UPDATE ON book_feature FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
