ALTER TABLE assessment_question
    ADD COLUMN difficulty_snapshot int;

UPDATE assessment_question aq
SET difficulty_snapshot = q.difficulty
FROM question q
WHERE q.id = aq.question_id;

ALTER TABLE assessment_question
    ALTER COLUMN difficulty_snapshot SET NOT NULL,
    ADD CONSTRAINT assessment_question_difficulty_snapshot_check
        CHECK (difficulty_snapshot BETWEEN 1 AND 5);

ALTER TABLE assessment_session
    ADD COLUMN completed_at timestamptz;

-- The previous release had no completion API, but preserve manually completed
-- development rows so an existing schema can still be upgraded safely.
UPDATE assessment_session
SET completed_at = updated_at
WHERE status = 'COMPLETED';

ALTER TABLE assessment_session
    ADD CONSTRAINT assessment_session_processing_ownership_check CHECK (
        (status = 'PROCESSING' AND attempt_id IS NOT NULL AND processing_expires_at IS NOT NULL)
        OR
        (status <> 'PROCESSING' AND attempt_id IS NULL AND processing_expires_at IS NULL)
    ),
    ADD CONSTRAINT assessment_session_completion_time_check CHECK (
        (status = 'COMPLETED') = (completed_at IS NOT NULL)
    );

CREATE INDEX assessment_session_latest_profile_idx
    ON assessment_session(user_id, topic_id, completed_at DESC, id DESC)
    WHERE status = 'COMPLETED';

CREATE TABLE reader_profile (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id bigint NOT NULL UNIQUE REFERENCES assessment_session(id),
    vocabulary double precision NOT NULL CHECK (vocabulary BETWEEN 0 AND 1),
    background_knowledge double precision NOT NULL CHECK (background_knowledge BETWEEN 0 AND 1),
    comprehension double precision NOT NULL CHECK (comprehension BETWEEN 0 AND 1),
    calculation_version varchar(80) NOT NULL CHECK (btrim(calculation_version) <> ''),
    evidence jsonb NOT NULL CHECK (jsonb_typeof(evidence) = 'object'),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TRIGGER reader_profile_updated BEFORE UPDATE ON reader_profile
FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
